### ISSUE TITLE
undefined index and variable

### ISSUE THREAD

**Issue by aaraya1516** [Ne00n/Ariane-Monitoring#10]
pretty sure I missed something on install, but I'm having this issue. Thing is, none of my graphs really work, except for general overview page.

[Sat Feb 18 22:05:54.762389 2017] [:error] [pid 29951] [client 1.14.00.1:56874] PHP Notice:  Undefined index: timestamp in /var/www/html/ariane/pages/dashboard.php on line 26, referer: https://site.com/ariane/index.php?page=dashboard?server=5?memory
[Sat Feb 18 22:05:54.762426 2017] [:error] [pid 29951] [client 1.14.00.1:56874] PHP Notice:  Undefined index: timeframe in /var/www/html/ariane/pages/dashboard.php on line 26, referer: https://site.com/ariane/index.php?page=dashboard?server=5?memory
[Sat Feb 18 22:05:54.763559 2017] [:error] [pid 29951] [client 1.14.00.1:56874] PHP Notice:  Undefined variable: count in /var/www/html/ariane/class/Server.php on line 149, referer: https://site.com/ariane/index.php?page=dashboard?server=5?memory

**Comment by Ne00n** [comment]
Sounds like the Agent is posting data to the API but the API refuses to accept the Data because it does not meet the requierments. Just run log into your machine, run the Agent, and view the Output, should say something like Invalid....

**Comment by aaraya1516** [comment]
So, it turns out that the data was being sent and saved. I got a return of "Okay".
The graphs would not appear because the path in file: [cpu.php](https://github.com/Ne00n/Ariane-Monitoring/blob/master/pages/dashboard/cpu.php )
@ line 16: `<script src="../content/js/cpu.js"></script>`
 I had to remove the `../`.

I have a feeling that I mis-configured something on install, or didn't understand the directory structure it should be in. Either way the only graphs that don't work are the network ones at: 
`/ariane/index.php?page=overview`
The php is constructing a javascript array that does not terminate, it has a hanging comma ','. @ line 96: [overview_graph.php](https://github.com/Ne00n/Ariane-Monitoring/blob/master/pages/overview_graph.php)

**Comment by Ne00n** [comment]
Well, currently I am not continue Developing that Project, If you found a fix let me know, I can recommend LibreNMS for such stuff.

As long the API says okay, that means all data is valid, also the Network data.
So maybe some JS link problem yea, feel free to open a merge request when you fixed it. Thanks mate.
