### ISSUE TITLE
Agent.sh issues

### ISSUE THREAD

**Issue by ricardo777** [Ne00n/Ariane-Monitoring#4]
Running Debian and Centos

I am getting errors like:

Centos

eth0: error fetching interface information: Device not found
cat: /sys/class/net/eth0/statistics/rx_bytes: No such file or directory
cat: /sys/class/net/eth0/statistics/tx_bytes: No such file or directory

Debian

venet0: error fetching interface information: Device not found

And agent does not trasnfer data to server.

**Comment by Ne00n** [comment]
Hey,

Unfortunately I never used CentOS, No idea how to fix that. When I have time I will look into that but could take a while. Maybe you can supply a fix for that.

Debian: agent.sh checks if eth0 exists if not it takes venet0 which is usually used by OpenVZ.
When you using a different network adapter you need to update agent.sh with the correct one.
Which one are you using?

If you see no Data, please go to: index.php?page=dashboard?logs and give us the Error message, if the Server has a valid key, you should see the Error message, since the API blocks any empty or not numeric posts.

Neoon.

**Comment by ricardo777** [comment]
I am busy with modifying the agent script.

I am changing the CPU to:

CPU=$(cat -n /proc/cpuinfo | grep '57' | cut -c 20-65);


Output is:

Intel(R) Xeon(R) CPU E5-1650 v3 @ 3.50GHz

But getting the error:

CPU contains invalid Letters

The standard line is:

cat /proc/cpuinfo | grep 'model name' | awk -F\: '{ print $2 }' | cut -d$'\n' -f1

Outputs:

 Intel(R) Xeon(R) CPU E5-1650 v3 @ 3.50GHz
 Intel(R) Xeon(R) CPU E5-1650 v3 @ 3.50GHz
 Intel(R) Xeon(R) CPU E5-1650 v3 @ 3.50GHz
 Intel(R) Xeon(R) CPU E5-1650 v3 @ 3.50GHz

But gives the same error.

For the IP I now use:

IP=$(ip route get 1 | awk '{print $NF;exit}');

**Comment by Ne00n** [comment]
Could you please tell me the OS?

Again, please go to: index.php?page=dashboard?logs and get me the Error, if you come along with the Error from the API, the Error is not Unique and has different meanings.

Because of obvious reasons, You can view the exact error in your logs.

**Comment by ricardo777** [comment]
DISTRIB_DESCRIPTION="Ubuntu 14.04.5 LTS"

Log only contains alot of line of: 

API	CPU Name contains invalid Letters!
API	CPU Name contains invalid Letters!

**Comment by Ne00n** [comment]
Seems like Ubuntu 14.04 duplicates outputs, something isnt right.

**Comment by Ne00n** [comment]
Seems to be a RegEx issue, trying to fix it now.

**Comment by Ne00n** [comment]
These Ubuntu issues should be fixed now, for Upgrading: https://github.com/Ne00n/Ariane-Monitoring/wiki/1.4.105

**Comment by ricardo777** [comment]
Hello,

I tested it out and now it works, only thing is the RX TX is not working but I am looking into that.

**Comment by Ne00n** [comment]
Usually because you have a Device which is eth0 or venet0 but there isnt your main traffic going over it.

**Comment by Ne00n** [comment]
I have a fix for this Network issue, pushing it soonTM, regarding CentOS i did open another ticket.

**Comment by Ne00n** [comment]
Pushed a Patch for these Network issues, it should detect the primary NIC now automatic, you only need to update your agent.sh, the API works fine with the new version.
